### ISSUE TITLE
create spreadsheet name

### ISSUE THREAD

**Issue by dgleba** [mila/pyoo#10]
I get this error.

```
    doc = desktop.create_spreadsheet('sheeta.ods')
TypeError: create_spreadsheet() takes 1 positional argument but 2 were given
```

What am I doing wrong?

**Comment by mila** [comment]
Function `create_spreadsheet` should not be called with file name.

**Comment by dgleba** [comment]
Thanks, 
The readme.md indicates using a filename may be possible.
