### ISSUE TITLE
LibreOffice stops working after launching script

### ISSUE THREAD

**Issue by jackgriffin63** [mila/pyoo#13]
Hello,
I wanted to report a problem.
I installed the pyoo library using pip and wrote a simple python script to test it
based on one of the provided examples.

`import os
import pyoo

os.popen(
        '/usr/lib/libreoffice/program/soffice --accept="socket,host=localhost,port=2002;urp;" --norestore --nologo '
        '--nodefault --headless')  # connect to LibreOffice

desktop = pyoo.Desktop('localhost', 2002)

doc = desktop.open_spreadsheet("./source01.ods")
sheet = doc.sheets[0]
sheet[0, 0].value = 1
sheet[1, 0].value = 2
sheet[2, 0].value = 3

doc.save('./done01.ods')  # saves the file as ODS
doc.close()`

It works as expected and without errors, but after launching it, LibreOffice stops working : it does not open any file
anymore and I must restart the system to make it work again.
Note that nor OpenOffice or Calc is listed in the current processes if I launch the **top** command.
I wonder if this is a known problem and if there is any solution.

My system is :
Kubuntu 21.04, LibreOffice Community 7.1.7.2, Python 3.9.5

Thank you in advance
Jack Griffin

**Comment by mila** [comment]
You start LibreOffice with a `--headless` option, which says that is should render no UI. My guess is that LibreOffice started from Python is not stopped, but it is not visible. I would try to terminate that process before a Python script ends.

In any case, I don't think that it is an issue that PyOO should handle, so I will close this issue.

**Comment by jackgriffin63** [comment]
I launched the script omitting the `--headless` option and now LibreOffice still works after launching the script, so you are right.
Still, as I mentioned in my first post, LibreOffice was not in the list of running processes.I guess it would've been if it was not visible but still running.
Please note that that option is mentioned in the example in [this page](https://pypi.org/project/pyoo/).
This is why I added in the script ;-).
Anyway, problem solved.
Thank you for your time and for your fast reply.
